services:
  - name: server
    buildCommand: cd server && npm install && npm build
    startCommand: cd server && npm start

  - name: client
    buildCommand: cd client && npm install && npm build
    startCommand: cd client && npm start
